### ISSUE TITLE
Please merge Release 6.1.3 with Angular 15 support

### ISSUE THREAD

**Issue by ebeling** [l0ll098/FirebaseUI-Angular#8]
@l0ll098 Many thanks for your great work, I want to use your library. Would you please merge the release 61.3  from original project?

**Comment by l0ll098** [comment]
Just released the updated version on npm!
Make sure to bump the `firebaseui-angular-i18n` dependency to version `6.1.3` and you should be good to go

**Comment by ebeling** [comment]
You are a Hero ! Thank you very much !!! :thumbsup: :clap:
